### ISSUE TITLE
redo install process

### ISSUE THREAD

**Issue by jaesivsm** [jaesivsm/JARR#5]
the bootstraping script (install.sh) is a mess and just doesn't work

redo conf, create a yaml file at creation 
create a install script asking basic config (url, admin login and password and stuff like that)

**Comment by dauving** [comment]
I think the install should be done in a virtualenv, this would be much cleaner.

**Comment by jaesivsm** [comment]
I'll put it up in the installation documentation but I don't think it's up to the project install script to create the virtual env.
Plus it would add a whole layer of complexity to both script and installation where I'd like to keep it as simple as possible.

**Comment by jaesivsm** [comment]
@dauving i pushed the new install procedure to the master branch, I'd be interested in some feedback if you may !

**Comment by dauving** [comment]
I just finished setting up JARR, yay !

Some comments :
- You maybe should precise if it's a python2 or 3 package, I wasn't sure at the beginning.
- You have inconsistencies in the command you give for setting up the database. Some time you use "aggregator" as database and other time "jarr".
- Postgresql asked me to remove the single quote here : ALTER USER '<youruser>' WITH.
- The dev packages of postgresql are needed on debian (postgresql-server-dev-9.4 as of jessie).
- You should speak about the possibility of compiling the JS file, it was throwing at me that I haven't the possibility to compile them during the install.
- The default port of postgresql is 5432, not 5433 (I hate you on this one).
- Adding informations about the OAUTH feature and readibility key in the README.md would be a good idea, during the install, I was knowing wat you were speaking because you show me this before, otherwise, I will be lost in space.

**Comment by jaesivsm** [comment]
Dully noted, will update documentation soon.
